api/urls.py
from rest_framework.authtoken import views
from django.urls import path, include
from rest_framework import routers
from api.views import (
    SessionCreateView,
    SessionUpdateView,
    TicketCreateView,
    SessionListView,
    FilmCreateView,
    HallCreateView,
    HallUpdateView,
    TicketListView,
    AuthViewSet,
)

router = routers.DefaultRouter(trailing_slash=False)
router.register('', AuthViewSet, basename='auth')

urlpatterns = [
    path('auth/', include(router.urls)),
    path('api-token-auth/', views.obtain_auth_token),
    path('sessions/', SessionListView.as_view(), name='session-list'),
    path('session/create/', SessionCreateView.as_view(), name='session-create'),
    path('session/update/<int:pk>/', SessionUpdateView.as_view(), name='session-update'),
    path('film/create/', FilmCreateView.as_view(), name='film-create'),
    path('hall/create/', HallCreateView.as_view(), name='hall-create'),
    path('hall/update/<int:pk>/', HallUpdateView.as_view(), name='hall-update'),
    path('tickets/', TicketListView.as_view(), name='ticket-list'),
    path('sessions/<int:session_pk>/book/<str:date_filter>/', TicketCreateView.as_view(), name='ticket-create'),
]

cinema/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.LoginPage.as_view(), name='login_page'),
    path('logout/', views.LogoutPage.as_view(), name='logout_page'),
    path('signup/', views.SignupPage.as_view(), name='signup_page'),
    path('create/hall/', views.CinemaHallCreatePage.as_view(), name='create_hall'),
    path('create/session/', views.SessionCreatePage.as_view(), name='create_session'),
    path('create/film/', views.FilmCreatePage.as_view(), name='create_film'),
    path('update/session/<int:pk>/', views.SessionUpdatePage.as_view(), name='update_session'),
    path('update/hall/<int:pk>/', views.HallUpdatePage.as_view(), name='update_hall'),
    path('book/ticket/<int:pk>/<str:date_filter>/', views.TicketBookPage.as_view(), name='book_ticket'),
    path('booked/tickets/', views.BookedTicketsPage.as_view(), name='booked_tickets'),
    path('api/halls/', views.hall_list_api, name='hall_list_api'),
    path('', views.SchedulePage.as_view(), name='schedule_page'),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('cinema.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cinema/models.py
from django.contrib.auth.models import AbstractUser
from datetime import datetime, date, timedelta
from django.db import models


class User(AbstractUser):
    total_spent = models.DecimalField(decimal_places=2, default=0, max_digits=12)
    last_activity = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"{self.username}"


class CinemaHall(models.Model):
    name = models.CharField(max_length=100)
    size = models.PositiveIntegerField()

    def __str__(self):
        return self.name


class Film(models.Model):
    name = models.CharField(max_length=100)
    genre = models.TextField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name


class Session(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE, related_name='session_film')
    hall = models.ForeignKey(CinemaHall, on_delete=models.CASCADE, related_name='session_hall')
    price = models.DecimalField(decimal_places=2, max_digits=12)
    start_time = models.TimeField(default=datetime.now().strftime("%H:%M"))
    end_time = models.TimeField(default=datetime.now().strftime("%H:%M"))
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(default=date.today)

    def __str__(self):
        return f'{self.film.name} from {self.start_date.strftime("%d")} to {self.end_date.strftime("%d, %Y")}'

    class Meta:
        ordering = ['start_date']

    def create_available(self, date):
        available_seats_obj, created = AvailableSeats.objects.get_or_create(session=self, date=date)
        return self.hall.size - available_seats_obj.occupied_seats

    def available_today(self):
        today = date.today()
        return self.create_available(today)

    def available_tomorrow(self):
        tomorrow = date.today() + timedelta(days=1)
        return self.create_available(tomorrow)


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    count_of_tickets = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(decimal_places=2, max_digits=12)
    data_session = models.DateField(default=date.today)
    data_creation = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} - {self.session.hall.name} - {self.session.start_time.strftime("%H:%M")}'

    class Meta:
        ordering = ['-data_creation']


class AvailableSeats(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    date = models.DateField(default=date.today)
    occupied_seats = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.session} - {self.date}"

    class Meta:
        unique_together = ('session', 'date')

cinema/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import get_user_model
from datetime import date, timedelta, datetime
from django.shortcuts import redirect
from django.contrib.auth import login
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.contrib import messages
from django.utils import timezone
from django.db.models import F
from django.views.generic import (
    CreateView,
    UpdateView,
    ListView,
)
from cinema.forms import (
    SignUpForm,
    CinemaHallForm,
    SessionForm,
    FilmForm
)
from .models import (
    AvailableSeats,
    CinemaHall,
    Session,
    Ticket,
    Film,
)

User = get_user_model()


# HOME PAGE
class SchedulePage(ListView):
    model = Session
    template_name = 'cinema/schedule.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date_filter = self.request.GET.get('date-filter', self.request.session.get('date-filter', 'today'))
        price_from = self.request.GET.get('price_from')
        price_to = self.request.GET.get('price_to')
        time_filter = self.request.GET.get('time-filter', 'end_time')
        sold_message = self.request.GET.get('sold_message')

        sessions = Session.objects.all()

        if date_filter == 'today':
            today = date.today()
            now = datetime.now().time()
            sessions = sessions.filter(
                start_date__lte=today,
                end_date__gte=today,
                start_time__gt=now)
        elif date_filter == 'tomorrow':
            tomorrow = date.today() + timedelta(days=1)
            sessions = sessions.filter(start_date__lte=tomorrow, end_date__gte=tomorrow)

        if price_from and price_to:
            sessions = sessions.filter(price__gte=price_from, price__lte=price_to)

        if time_filter == 'end_time':
            sessions = sessions.order_by('-start_time')
        elif time_filter == 'start_time':
            sessions = sessions.order_by('start_time')

        if sold_message:
            messages.error(self.request, 'All tickets for this session have already been sold!')

        context['object_list'] = sessions
        context['date_filter'] = date_filter
        context['time_filter'] = time_filter
        self.request.session['date-filter'] = date_filter

        return context


# LOGIN
class LoginPage(LoginView):
    template_name = 'cinema/login.html'

    def get_success_url(self):
        return reverse_lazy('schedule_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for field in ('username', 'password'):
            context['form'].fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': f'Enter {field.capitalize()}'
            })
        return context

    def form_valid(self, form):
        response = super().form_valid(form)

        self.request.user.last_activity = timezone.now()
        self.request.user.save()

        return response


# LOG OUT
class LogoutPage(LoginRequiredMixin, LogoutView):
    next_page = reverse_lazy('schedule_page')
    login_url = 'login/'


# SIGN UP
class SignupPage(CreateView):
    form_class = SignUpForm
    template_name = 'cinema/signup.html'

    def form_valid(self, form):
        self.object = form.save()
        login(self.request, self.object)
        return redirect('schedule_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for field in ('username', 'email', 'password1', 'password2'):
            context['form'].fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': f'Enter {field.capitalize()}'
            })
        return context


class AdminRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


# CREATE FILM(ADMIN)
class FilmCreatePage(AdminRequiredMixin, CreateView):
    model = Film
    form_class = FilmForm
    template_name = 'cinema/create_film.html'

    def get_success_url(self):
        return reverse_lazy('create_film')

    def form_valid(self, form):
        messages.success(self.request, 'Film successfully created!')
        return super().form_valid(form)


# CREATE HALL(ADMIN)
class CinemaHallCreatePage(AdminRequiredMixin, CreateView):
    model = CinemaHall
    form_class = CinemaHallForm
    template_name = 'cinema/create_hall.html'

    def get_success_url(self):
        return reverse_lazy('create_hall')

    def form_valid(self, form):
        messages.success(self.request, 'Cinema hall successfully created!')
        return super().form_valid(form)


# CREATE SESSION(ADMIN)
class SessionCreatePage(AdminRequiredMixin, CreateView):
    model = Session
    form_class = SessionForm
    template_name = 'cinema/create_session.html'

    def get_success_url(self):
        return reverse_lazy('create_session')

    def form_valid(self, form):
        messages.success(self.request, 'Session successfully created!')
        return super().form_valid(form)


# UPDATE SESSION(ADMIN)
class SessionUpdatePage(AdminRequiredMixin, UpdateView):
    model = Session
    form_class = SessionForm
    template_name = 'cinema/update_session.html'

    def get_success_url(self):
        messages.success(self.request, 'Session successfully updated!')
        return reverse_lazy('schedule_page')

    def form_valid(self, form):
        session_pk = self.kwargs['pk']

        bought_tickets = Ticket.objects.filter(session__pk=session_pk).count()

        if bought_tickets > 0:
            messages.error(self.request, 'Tickets have already been booked for this session!')
            return redirect('schedule_page')

        return super().form_valid(form=form)


# UPDATE HALL(ADMIN)
class HallUpdatePage(AdminRequiredMixin, UpdateView):
    model = CinemaHall
    form_class = CinemaHallForm
    template_name = 'cinema/update_hall.html'

    def get_success_url(self):
        messages.success(self.request, 'Hall successfully updated!')
        return reverse_lazy('schedule_page')

    def form_valid(self, form):
        hall_pk = self.kwargs['pk']
        today = date.today()

        bought_tickets = Ticket.objects.filter(session__hall__pk=hall_pk, session__end_date__gt=today).count()

        if bought_tickets > 0:
            messages.error(self.request, 'Tickets have already been booked in this hall!')
            return redirect('schedule_page')

        return super().form_valid(form=form)


# LIST OF HALLS (JSON)
def hall_list_api(request):
    halls = CinemaHall.objects.values('id', 'name')
    return JsonResponse({'halls': list(halls)})


# BOOK TICKETS(USER)
class TicketBookPage(LoginRequiredMixin, CreateView):
    login_url = 'login/'
    model = Ticket
    fields = ['count_of_tickets']
    template_name = 'cinema/book_tickets.html'

    def get_success_url(self):
        messages.success(self.request, f'The tickets was successfully booked for!')
        return reverse_lazy('schedule_page')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        session = Session.objects.get(pk=self.kwargs['pk'])
        data_filter = self.kwargs['date_filter']
        available_seats = session.available_tomorrow() if data_filter == 'tomorrow' else session.available_today()

        context['session'] = session
        context['available_seats'] = available_seats
        return context

    def form_valid(self, form):
        session_pk = self.kwargs['pk']
        session = Session.objects.get(pk=session_pk)
        count_of_tickets = form.cleaned_data['count_of_tickets']
        date_filter = self.kwargs['date_filter']
        available_seats = session.available_tomorrow() if date_filter == 'tomorrow' else session.available_today()
        user = self.request.user

        if count_of_tickets <= 0:
            messages.error(self.request, "Count of tickets must be greater than zero!")
            return redirect('schedule_page')

        if available_seats < count_of_tickets:
            messages.error(self.request, 'Not enough available seats!')
            return redirect('schedule_page')

        session_date = date.today() + timedelta(days=1) if date_filter == 'tomorrow' else date.today()

        available_seats_obj, created = AvailableSeats.objects.get_or_create(session=session, date=session_date)
        available_seats_obj.occupied_seats += count_of_tickets
        available_seats_obj.save()

        total_price = count_of_tickets * session.price
        self.request.user.total_spent = F('total_spent') + total_price

        self.object = form.save(commit=False)
        self.object.user = user
        self.object.session = session
        self.object.count_of_tickets = count_of_tickets
        self.object.total_price = total_price
        self.object.data_session = session_date
        self.object.save()

        return super().form_valid(form=form)


# BOOKED TICKETS(USER)
class BookedTicketsPage(LoginRequiredMixin, ListView):
    login_url = 'login/'
    model = Ticket
    template_name = 'cinema/booked_tickets.html'
    paginate_by = 5

    def get_queryset(self):
        return Ticket.objects.filter(user=self.request.user)

templates/cinema/available.html
{% if available_seats == 0 %}
    <form method="get" action="{% url 'schedule_page' %}">
        <input type="submit" name="sold_message" class="btn btn-secondary session-button" value="Sold">
        <p class="session-time session-button">Available seats: {{ available_seats }}</p>
    </form>
{% else %}
    <form method="post" action="{% url 'book_ticket' session.pk date_filter %}">
        {% csrf_token %}
        <input type="submit" class="btn btn-warning session-button login-button" value="Book">
        <p class="session-time session-button">Available seats: {{ available_seats }}</p>
    </form>
{% endif %}

templates/cinema/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Home Page{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'cinema/css/cinema.css' %}">
</head>
<body>
    <nav class="my_cont">
        <div class="elements">
            <ul class="navigation_mar">
                <li class="line">
                    <a href="{% url 'schedule_page' %}" class="nav_link_px {% if not user.is_superuser and user.is_active %}active{% endif %}" aria-current="page">Schedule</a>
                </li>
                {% if user.is_superuser %}
                    <li class="line"><a href="{% url 'create_film' %}" class="nav_link_px">Create Film</a></li>
                    <li class="line"><a href="{% url 'create_hall' %}" class="nav_link_px">Create Cinema-Hall</a></li>
                    <li class="line"><a href="{% url 'create_session' %}" class="nav_link_px">Create Session</a></li>
                    <li class="line"><a href="#" class="nav_link_px" data-bs-toggle="modal" data-bs-target="#updateHallModal">Update Hall</a></li>
                {% elif user.is_active %}
                    <li class="line"><a href="{% url 'booked_tickets' %}" class="nav_link_px">Booked Tickets</a></li>
                {% endif %}
            </ul>

            {% if user.is_authenticated %}
                <ul class="navigation">
                    <span class="username">{{ user.username }}</span>
                </ul>
                <form method="post" action="{% url 'logout_page' %}">
                    {% csrf_token %}
                    <button class="btn btn-primary login-button" type="submit" >Log Out</button>
                </form>
            {% else %}
                <ul class="navigation">
                    <li class="line"><a href="{% url 'login_page' %}" class="nav_link_px">Login</a></li>
                    <li class="line"><a href="{% url 'signup_page' %}" class="nav_link_px">Sign up</a></li>
                </ul>
            {% endif %}
        </div>
    </nav>
    <br>
    <main>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
    </main>

    <!-- Modal -->
    <div class="modal fade" id="updateHallModal" tabindex="-1" aria-labelledby="updateHallModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="updateHallModalLabel">Select Hall to Update</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <ul id="hallList">
                        <!-- List of halls will be loaded here dynamically -->
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            // Fetch the list of halls and append to the modal
            fetch("{% url 'hall_list_api' %}")
                .then(response => response.json())
                .then(data => {
                    const hallList = document.getElementById('hallList');
                    data.halls.forEach(hall => {
                        const listItem = document.createElement('li');
                        const link = document.createElement('a');
                        link.href = `{% url 'update_hall' 0 %}`.replace('0', hall.id);
                        link.textContent = hall.name;
                        listItem.appendChild(link);
                        hallList.appendChild(listItem);
                    });
                });
        });
    </script>
</body>
</html>

templates/cinema/book_tickets.html
{% extends 'cinema/base.html' %}

{% block title %}Booking Page{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="error-message">{{ message }}</div>
            {% endif %}
        {% endfor %}

        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="success-message" style="color: limegreen; margin-bottom: 5px">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="container">
        <div class="session-details d-flex">
            <div class="session-image-container">
                <img src="{{ session.film.image.url}}" alt="{{ session.film.name }}" class="session-image-v2">
            </div>
            <div class="session-info">
                <h1>{{session.film.name}}</h1>
                <br>
                <p class="session-price">Genre: {{ session.film.genre }}</p>
                <p class="session-date">{{ session.start_date|date:"M d" }} - {{ session.end_date|date:"M d, Y" }}</p>
                <p class="session-time">{{ session.start_time|time:"H:i" }} - {{ session.end_time|time:"H:i" }}</p>
                <p class="session-time">{{ session.hall.name }}</p>
                <p class="session-price">Price: ${{ session.price }}</p>
                <br>
                <p class="session-time session-button" style="margin-left: 30px;">Available seats: {{ available_seats }}</p>
                <form method="post">
                    {% csrf_token %}
                    <input type="number" name="count_of_tickets" class="form-control" style="width: 71%; display: inline-block;" placeholder="Enter count of tickets" min="1" required>
                    <button type="submit" class="btn btn-primary login-button" style="margin-bottom: 4px;">Book</button>
                </form>
                <br>

                <a href="{% url 'schedule_page' %}" class="nav_link_px_login">Cancel booking</a>

            </div>
        </div>
    </div>
{% endblock %}

templates/cinema/booked_tickets.html
{% extends 'cinema/base.html' %}

{% block title %}My Booked Tickets{% endblock %}

{% block content %}
   <div class="container">

       <h2 class="my-3">My Booked Tickets</h2>
       <h6 style="text-align: right;">Total Spent: ${{ user.total_spent }}</h6>

        <table class="table table-bordered table-tickets">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Film</th>
                    <th>Cinema Hall</th>
                    <th>Date</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    <th>Tickets Count</th>
                    <th>Total Price</th>
                </tr>
            </thead>
            <tbody>
                {% for ticket in object_list %}
                    <tr>
                        <td class="table-image">
                            <img src="{{ ticket.session.film.image.url }}" alt="{{ ticket.session.film.name }}" class="img-fluid rounded-start">
                        </td>
                        <td>{{ ticket.session.film.name }}</td>
                        <td>{{ ticket.session.hall.name }}</td>
                        <td>{{ ticket.data_session }}</td>
                        <td>{{ ticket.session.start_time }}</td>
                        <td>{{ ticket.session.end_time }}</td>
                        <td>{{ ticket.count_of_tickets }}</td>
                        <td>{{ ticket.total_price }}</td>
                    </tr>
              {% endfor %}
            </tbody>
        </table>

        {% if page_obj.paginator.num_pages > 1 %}
            <nav aria-label="...">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}

    </div>
{% endblock %}

templates/cinema/create_film.html
{% extends 'cinema/base.html' %}

{% block title %}Create Film{% endblock %}

{% block content %}

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="success-message" style="color: limegreen; margin-bottom: 5px">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div class="features">
        <h1>Create Film</h1>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <label for="id_name">Enter Film Name:</label><br>
            {{ form.name }}<br>
            {% for error in form.name.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}

            <label for="id_genre">Enter Film Genre:</label><br>
            {{ form.genre }}<br>
            {% for error in form.genre.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}

            {{ form.image }}<br>
            {% for error in form.image.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}

            <button class="btn btn-primary login-button" type="submit">Create</button>
        </form>

    <a href="{% url 'schedule_page' %}" class="nav_link_px_login">Cancel creation</a>
    </div>
{% endblock %}

templates/cinema/create_hall.html
{% extends 'cinema/base.html' %}

{% block title %}Create Cinema Hall{% endblock %}

{% block content %}
    <div class="features">
        <h1>Create Cinema Hall</h1>
        <br>

        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="success-message" style="color: limegreen; margin-bottom: 5px">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <form method="post">
            {% csrf_token %}

            {% for error in form.name.errors %}
                <p class="error-message">{{ error }}</p>
            {% endfor %}

            <label for="id_name">Enter Hall Name:</label><br>
            {{ form.name }}<br>
            <label for="id_size">Enter Hall Size:</label><br>
            {{ form.size }}<br>

            <button class="btn btn-primary login-button" type="submit">Create</button>
        </form>
    <a href="{% url 'schedule_page' %}" class="nav_link_px_login">Cancel creation</a>
    </div>
{% endblock %}

templates/cinema/create_session.html
{% extends 'cinema/base.html' %}

{% block title %}Create Session{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success' %}
                <div class="success-message" style="color: limegreen; margin-bottom: 5px">{{ message }}</div>
            {% endif %}
        {% endfor %}
    {% endif %}

    <div class="features">
        <h1>Create Session</h1>
        <br>
        <form method="post">
            {% csrf_token %}

            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="error-message">{{ error }}</div>
                {% endfor %}
            {% endif %}

            <label for="id_film">Choose a Film:</label><br>
            {{ form.film }}<br>

            <label for="id_hall">Choose a Hall:</label><br>
            {{ form.hall }}<br>

            <label for="id_price">Enter the Session Price:</label><br>
            {{ form.price }}<br>

            <label for="id_start_time">Enter the Start Time:</label><br>
            {{ form.start_time }}<br>

            <label for="id_end_time">Enter the End Time:</label><br>
            {{ form.end_time }}<br>

            <label for="id_start_date">Enter the Start Date:</label><br>
            {{ form.start_date }}<br>

            <label for="id_end_date">Enter the End Date:</label><br>
            {{ form.end_date }}<br>

            <button class="btn btn-primary login-button" type="submit">Create</button>
        </form>
    <a href="{% url 'schedule_page' %}" class="nav_link_px_login">Cancel creation</a>
    </div>
{% endblock %}

templates/cinema/update_hall.html
{% extends 'cinema/base.html' %}

{% block title %}Update Hall{% endblock %}

{% block content %}
    <div class="features">
        <h1>Update Hall</h1>

        <br>
        <form method="post">

            {% if form.non_field_errors %}
                <ul>
                    {% for error in form.non_field_errors %}
                        <li class="error-message">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% csrf_token %}
            <label for="id_name">Enter Hall Name:</label><br>
            {{ form.name }}
            <br>

            <label for="id_size">Enter Hall Size:</label><br>
            {{ form.size }}
            <br>
            <button class="btn btn-primary login-button" type="submit">Update</button>
        </form>
    <a href="{% url 'schedule_page' %}" class="nav_link_px_login">Cancel update</a>
    </div>
{% endblock %}

templates/cinema/update_session.html
{% extends 'cinema/base.html' %}

{% block title %}Update Session{% endblock %}

{% block content %}
    <div class="features">
        <h1>Update Session</h1>

        <br>
        <form method="post">

            {% if form.non_field_errors %}
                <ul>
                    {% for error in form.non_field_errors %}
                        <li class="error-message">{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% csrf_token %}
            <label for="id_film">Choose a Film:</label><br>
            {{ form.film }}
            <br>
            <label for="id_hall">Choose a Hall:</label><br>
            {{ form.hall }}
            <br>
            <label for="id_price">Enter the Session Price:</label><br>
            {{ form.price }}
            <br>
            <label for="id_start_time">Enter the Start Time:</label><br>
            {{ form.start_time }}
            <br>
            <label for="id_end_time">Enter the End Time:</label><br>
            {{ form.end_time }}
            <br>
            <label for="id_start_date">Enter the Start Date:</label><br>
            {{ form.start_date }}
            <br>
            <label for="id_end_date">Enter the End Date:</label><br>
            {{ form.end_date }}
            <br>
            <button class="btn btn-primary login-button" type="submit">Update</button>
        </form>
    <a href="{% url 'schedule_page' %}" class="nav_link_px_login">Cancel update</a>
    </div>
{% endblock %}